# Generated by Django 2.2.10 on 2020-04-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='материал')),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('summary', models.CharField(max_length=1000, verbose_name='описание')),
                ('price', models.FloatField(verbose_name='цена')),
                ('qrcode', models.CharField(max_length=300, verbose_name='штрихкод')),
                ('materials', models.ManyToManyField(to='catalog.Material', verbose_name='материал')),
                ('size', models.ManyToManyField(to='catalog.Size', verbose_name='размер')),
            ],
        ),
    ]
